name: Generate
on:
  push:
    branches: [main]
  workflow_dispatch:
    # nothing here

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python & Build
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install pillow
          cd src
          python3 -m thumbnail-generator

      - name: Upload Thumbnails
        uses: actions/upload-artifact@v4
        with:
          name: 'thumbnails'
          path: |
            out/*
          retention-days: 1
